name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os:
          - ubuntu-latest
        php:
          - 7.3
          - 7.4
          - 8.0
          - 8.1
          - 8.2
    name: Test - php:${{ matrix.php }}; ${{ matrix.os }};
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@2.25.1
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, gd, pdo_mysql, json, mbstring, pcre, session
          coverage: none
          tools: composer:v2

      - name: Composer install
        shell: bash
        run: composer install --prefer-source --no-interaction

      - name: Kahlan tests
        shell: bash
        run: ./vendor/bin/kahlan
